apiVersion: v1
kind: Service
metadata:
  name: wissen-backend-service
spec:
  type: NodePort
  selector:
    app: wissen-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wissen-backend-deployment
  labels:
    app: wissen-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wissen-backend
  template:
    metadata:
      labels:
        app: wissen-backend
    spec:
      containers:
        - name: wissen-backend
          image: ajaxsoften/wissen-backend:$COMMIT_SHA1
          ports:
            - containerPort: 80
              name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wissen-backend-http-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /public
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - api.wissen.team
      secretName: wissen-backend-tls
  rules:
    - host: api.wissen.team
      http:
        paths:
          - backend:
              serviceName: wissen-backend-service
              servicePort: 80
